// Generated with the help of https://github.com/jdan/markov.rb
//
//   m = Markov.new(options[:n])
//   names = STDIN.read.split.map &:chomp
//   names.each do |name|
//     m.digest(name)
//   end
//
// + require 'json'
// + puts m.chain.to_json

exports.chain = {
  start: [
    "hy",
    "he",
    "li",
    "be",
    "bo",
    "ca",
    "ni",
    "ox",
    "fl",
    "ne",
    "so",
    "ma",
    "al",
    "si",
    "ph",
    "su",
    "ch",
    "ar",
    "po",
    "ca",
    "sc",
    "ti",
    "va",
    "ch",
    "ma",
    "ir",
    "co",
    "ni",
    "co",
    "zi",
    "ga",
    "ge",
    "ar",
    "se",
    "br",
    "kr",
    "ru",
    "st",
    "yt",
    "zi",
    "ni",
    "mo",
    "te",
    "ru",
    "rh",
    "pa",
    "si",
    "ca",
    "in",
    "ti",
    "an",
    "te",
    "io",
    "xe",
    "ca",
    "ba",
    "la",
    "ce",
    "pr",
    "ne",
    "pr",
    "sa",
    "eu",
    "ga",
    "te",
    "dy",
    "ho",
    "er",
    "th",
    "yt",
    "lu",
    "ha",
    "ta",
    "tu",
    "rh",
    "os",
    "ir",
    "pl",
    "go",
    "me",
    "th",
    "le",
    "bi",
    "po",
    "as",
    "ra",
    "fr",
    "ra",
    "ac",
    "th",
    "pr",
    "ur",
    "ne",
    "pl",
    "am",
    "cu",
    "be",
    "ca",
    "ei",
    "fe",
    "me",
    "no",
    "la",
    "ru",
    "du",
    "se",
    "bo",
    "ha",
    "me",
    "da",
    "ro",
    "co",
    "ni",
    "fl",
    "mo",
    "li",
    "te",
    "og",
  ],
  hy: ["yd"],
  yd: ["dr"],
  dr: ["ro"],
  ro: [
    "og",
    "on",
    "og",
    "om",
    "on",
    "om",
    "on",
    "om",
    "op",
    "os",
    "ot",
    "oe",
    "ov",
  ],
  og: ["ge", "ge", "ga"],
  ge: ["en", "en", "en", "er", "en"],
  en: [
    "end",
    "end",
    "end",
    "ni",
    "ni",
    "nu",
    "ni",
    "no",
    "end",
    "ni",
    "nd",
    "nc",
    "nt",
    "ni",
    "nn",
  ],
  he: ["el", "en", "en", "er"],
  el: ["li", "end", "le", "ll", "li", "le", "li"],
  li: ["iu", "it", "iu", "ic", "iu", "in", "iu", "iu", "iu", "if", "iu", "iv"],
  iu: [
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
    "um",
  ],
  um: [
    "end",
    "end",
    "end",
    "end",
    "end",
    "mi",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
  ],
  it: ["th", "tr", "ta", "tn"],
  th: ["hi", "he", "ha", "hi", "hu", "ha", "end", "ho", "he"],
  hi: ["iu", "iu"],
  be: ["er", "er", "el"],
  er: [
    "ry",
    "end",
    "rm",
    "end",
    "ri",
    "rb",
    "rb",
    "rb",
    "rc",
    "ri",
    "rk",
    "rm",
    "rf",
    "ri",
    "rn",
    "ro",
    "rm",
  ],
  ry: ["yl", "yp", "end"],
  yl: ["ll"],
  ll: ["li", "li", "la", "lu", "li"],
  bo: ["or", "on", "or", "oh"],
  or: ["ro", "ri", "ru", "ri", "ri", "rn", "rd", "rg", "ri"],
  on: [
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "nt",
    "ni",
    "ny",
    "end",
    "ni",
    "end",
    "ni",
    "ni",
    "end",
  ],
  ca: ["ar", "al", "an", "ad", "ae", "al"],
  ar: ["rb", "rg", "rs", "ri", "ri", "rm"],
  rb: ["bo", "bi", "bi", "bi"],
  ni: [
    "it",
    "iu",
    "iu",
    "ic",
    "iu",
    "ic",
    "iu",
    "iu",
    "io",
    "iu",
    "iu",
    "iu",
    "iu",
    "iu",
    "iu",
    "iu",
    "iu",
    "iu",
    "iu",
    "iu",
    "iu",
    "iu",
    "iu",
    "ic",
    "ih",
    "iu",
  ],
  tr: ["ro", "ro", "ri"],
  ox: ["xy"],
  xy: ["yg"],
  yg: ["ge"],
  fl: ["lu", "le"],
  lu: ["uo", "um", "ur", "ut", "um", "ut"],
  uo: ["or"],
  ri: [
    "in",
    "in",
    "iu",
    "iu",
    "iu",
    "iu",
    "iu",
    "id",
    "iu",
    "ic",
    "iu",
    "iu",
    "iu",
    "iu",
  ],
  in: [
    "ne",
    "ni",
    "ne",
    "nc",
    "ne",
    "nd",
    "end",
    "ne",
    "ni",
    "nu",
    "ne",
    "ni",
    "ni",
    "ns",
    "ni",
    "ne",
  ],
  ne: [
    "end",
    "eo",
    "es",
    "end",
    "es",
    "end",
    "et",
    "end",
    "eo",
    "end",
    "ep",
    "er",
    "es",
    "end",
    "es",
  ],
  eo: ["on", "od", "od"],
  so: ["od", "on"],
  od: ["di", "di", "di", "dy", "dy"],
  di: ["iu", "iu", "iu", "iu", "iu", "iu", "iu", "in", "iu", "iu", "iu"],
  ma: ["ag", "an", "an", "ar"],
  ag: ["gn"],
  gn: ["ne"],
  es: ["si", "se", "si", "ss", "ss"],
  si: ["iu", "il", "iu", "il", "iu", "iu", "iu", "in"],
  al: ["lu", "lc", "lt", "ll", "ll", "lu", "ll", "li"],
  mi: ["in", "iu", "in", "iu", "iu", "iu", "iu", "iu", "iu"],
  il: ["li", "lv"],
  ic: ["co", "ck", "end", "ci", "ci"],
  co: ["on", "ob", "op", "on", "op", "ov"],
  ph: ["ho", "ho"],
  ho: ["os", "or", "od", "ol", "or", "on"],
  os: ["sp", "si", "sm", "sc"],
  sp: ["ph", "pr"],
  ru: ["us", "ub", "ut", "ut"],
  us: ["end"],
  su: ["ul"],
  ul: ["lf", "li"],
  lf: ["fu"],
  fu: ["ur"],
  ur: ["end", "ri", "ro", "ry", "ra", "ri"],
  ch: ["hl", "hr", "hn"],
  hl: ["lo"],
  lo: ["or", "on"],
  rg: ["go", "gi"],
  go: ["on", "ol"],
  po: ["ot", "ol"],
  ot: ["ta", "ta"],
  ta: ["as", "an", "an", "al", "at", "ac", "ad"],
  as: ["ss", "se", "st", "ss"],
  ss: ["si", "si", "si", "so"],
  lc: ["ci"],
  ci: ["iu", "iu", "iu", "iu", "iu"],
  sc: ["ca", "co"],
  an: [
    "nd",
    "ni",
    "na",
    "ng",
    "ne",
    "ni",
    "nt",
    "nt",
    "nu",
    "nt",
    "nc",
    "ni",
    "ne",
  ],
  nd: ["di", "di", "de"],
  ti: ["it", "iu", "iu", "in", "im", "iu", "in", "in", "in", "in", "iu"],
  va: ["an"],
  na: ["ad"],
  ad: ["di", "di", "dm", "do", "end", "do", "di", "dt"],
  hr: ["ro", "ri"],
  om: ["mi", "mi", "me"],
  ng: ["ga", "gs"],
  ga: ["an", "al", "ad", "an"],
  se: ["end", "en", "el", "eo", "ea"],
  ir: ["ro", "rc", "ri"],
  ob: ["ba", "bi", "be"],
  ba: ["al", "ar"],
  lt: ["end"],
  ck: ["ke"],
  ke: ["el", "el"],
  op: ["pp", "pi", "pe"],
  pp: ["pe"],
  pe: ["er", "er"],
  zi: ["in", "ir"],
  nc: ["end", "ci", "ci"],
  rm: ["ma", "mi", "ms", "mo"],
  rs: ["se"],
  le: ["en", "ea", "ev", "er"],
  br: ["ro"],
  kr: ["ry"],
  yp: ["pt"],
  pt: ["to", "tu"],
  to: ["on", "on"],
  ub: ["bi", "bn"],
  bi: ["id", "iu", "iu", "iu", "iu", "is"],
  id: ["di", "di"],
  st: ["tr", "te", "ta", "te", "ta"],
  nt: ["ti", "ti", "th", "ta", "tg"],
  yt: ["tt", "tt"],
  tt: ["tr", "te"],
  rc: ["co", "cu"],
  io: ["ob", "od"],
  mo: ["ol", "on", "os", "or"],
  ol: ["ly", "li", "lm", "ld", "lo"],
  ly: ["yb"],
  yb: ["bd"],
  bd: ["de"],
  de: ["en", "el"],
  nu: ["um", "um", "um"],
  te: ["ec", "el", "er", "er", "et", "en", "ei", "en"],
  ec: ["ch"],
  hn: ["ne"],
  et: ["ti", "th", "ti"],
  ut: ["th", "te", "th", "to", "th"],
  rh: ["ho", "he"],
  pa: ["al"],
  la: ["ad", "an", "at", "aw"],
  lv: ["ve"],
  ve: ["er", "er"],
  dm: ["mi"],
  im: ["mo"],
  ny: ["end"],
  xe: ["en"],
  no: ["on", "ob"],
  ae: ["es"],
  ha: ["an", "af", "al", "as"],
  ce: ["er"],
  pr: ["ra", "ro", "ro", "ro"],
  ra: ["as", "ad", "an", "ad", "an"],
  dy: ["ym", "ym", "ys"],
  ym: ["mi", "mi"],
  me: ["et", "er", "er", "en", "ei"],
  sa: ["am"],
  am: ["ma", "me"],
  eu: ["ur"],
  pi: ["iu"],
  do: ["ol", "on"],
  ys: ["sp"],
  lm: ["mi"],
  hu: ["ul"],
  af: ["fn"],
  fn: ["ni"],
  tu: ["un", "un"],
  un: ["ng", "ni"],
  gs: ["st"],
  sm: ["mi", "mu"],
  pl: ["la", "lu"],
  at: ["ti", "ti"],
  ld: ["end"],
  cu: ["ur", "ur"],
  ea: ["ad", "ab"],
  is: ["sm"],
  mu: ["ut"],
  fr: ["ra"],
  ac: ["ct", "ct"],
  ct: ["ti", "ti"],
  ep: ["pt"],
  rk: ["ke"],
  if: ["fo"],
  fo: ["or", "or"],
  rn: ["ni", "ni"],
  ei: ["in", "in", "it"],
  ns: ["st"],
  fe: ["er"],
  ev: ["vi"],
  vi: ["iu", "iu", "iu"],
  aw: ["wr"],
  wr: ["re"],
  re: ["en"],
  rf: ["fo"],
  rd: ["di"],
  du: ["ub"],
  bn: ["ni"],
  ab: ["bo"],
  gi: ["iu"],
  oh: ["hr"],
  tn: ["ne"],
  da: ["ar"],
  ms: ["st"],
  dt: ["ti"],
  oe: ["en"],
  tg: ["ge"],
  ih: ["ho"],
  ov: ["vi", "vi"],
  iv: ["ve"],
  nn: ["ne"],
};

exports.elements = new Set([
  "hydrogen",
  "helium",
  "lithium",
  "beryllium",
  "boron",
  "carbon",
  "nitrogen",
  "oxygen",
  "fluorine",
  "neon",
  "sodium",
  "magnesium",
  "aluminium",
  "silicon",
  "phosphorus",
  "sulfur",
  "chlorine",
  "argon",
  "potassium",
  "calcium",
  "scandium",
  "titanium",
  "vanadium",
  "chromium",
  "manganese",
  "iron",
  "cobalt",
  "nickel",
  "copper",
  "zinc",
  "gallium",
  "germanium",
  "arsenic",
  "selenium",
  "bromine",
  "krypton",
  "rubidium",
  "strontium",
  "yttrium",
  "zirconium",
  "niobium",
  "molybdenum",
  "technetium",
  "ruthenium",
  "rhodium",
  "palladium",
  "silver",
  "cadmium",
  "indium",
  "tin",
  "antimony",
  "tellurium",
  "iodine",
  "xenon",
  "caesium",
  "barium",
  "lanthanum",
  "cerium",
  "praseodymium",
  "neodymium",
  "promethium",
  "samarium",
  "europium",
  "gadolinium",
  "terbium",
  "dysprosium",
  "holmium",
  "erbium",
  "thulium",
  "ytterbium",
  "lutetium",
  "hafnium",
  "tantalum",
  "tungsten",
  "rhenium",
  "osmium",
  "iridium",
  "platinum",
  "gold",
  "mercury",
  "thallium",
  "lead",
  "bismuth",
  "polonium",
  "astatine",
  "radon",
  "francium",
  "radium",
  "actinium",
  "thorium",
  "protactinium",
  "uranium",
  "neptunium",
  "plutonium",
  "americium",
  "curium",
  "berkelium",
  "californium",
  "einsteinium",
  "fermium",
  "mendelevium",
  "nobelium",
  "lawrencium",
  "rutherfordium",
  "dubnium",
  "seaborgium",
  "bohrium",
  "hassium",
  "meitnerium",
  "darmstadtium",
  "roentgenium",
  "copernicium",
  "nihonium",
  "flerovium",
  "moscovium",
  "livermorium",
  "tennessine",
  "oganesson",
]);
